apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  labels:
    app: aggregator
spec:
  selector:
    app: aggregator
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "aggregator-config-maps"
  namespace: default
  labels: 
    app: aggregator
data:
  QUOTES_USER_URL: "http://user-service"
  QUOTES_ORDER_URL: "http://order-service"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
  labels:
    app: aggregator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: aggregator-container
        image: kkaggarwal/aggregator-service:0.0.1
        ports:
        - containerPort: 8082
        env:
          - name: QUOTES_USER_URL
            valueFrom:
                configMapKeyRef:
                  name: "aggregator-config-maps"
                  key: QUOTES_USER_URL
          - name: QUOTES_ORDER_URL
            valueFrom:
                configMapKeyRef:
                  name: aggregator-config-maps
                  key: QUOTES_ORDER_URL